server:
  port: 8001

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id:  cloud-provider-hystrix-payment

spring:
  application:
    name: cloud-provider-hystrix-payment
