server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-provider-payment   #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**   #断言,路径相匹配的进行路由

        - id: payment_routh2
          uri: lb://cloud-provider-payment
          predicates:
            - Path=/payment/lb/**   #断言,路径相匹配的进行路由
            - After=2020-10-25T23:09:38.528+08:00[Asia/Shanghai]


eureka:
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: cloudgateway9527
    prefer-ip-address: true

